/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kentaro.maeda' at '17/02/01 11:19' with Gradle 2.13
 *
 * @author kentaro.maeda, @date 17/02/01 11:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
