SET @baseDate = '20170321';
SELECT SQL_NO_CACHE * FROM (
    SELECT INTEREST_COUNT,COUNT(1) CNT FROM (SELECT
        C.ID, LAST_NAME, FIRST_NAME, BIRTHDAY, LEFT(@baseDate,4)-LEFT(BIRTHDAY,4)+LEAST(SIGN(RIGHT(@baseDate,4)-RIGHT(BIRTHDAY,4)),0),
    CASE WHEN GENDER = 0 THEN 'M' ELSE 'F' END, COUNT(1) INTEREST_COUNT
    FROM
        M_CUSTOMER C JOIN T_CUSTOMER_INTEREST CI JOIN M_INTEREST R
        WHERE CI.CUSTOMER = C.ID AND R.ID = CI.INTEREST AND
    LEFT(@baseDate,4)-LEFT(BIRTHDAY,4)+LEAST(SIGN(RIGHT(@baseDate,4)-RIGHT(BIRTHDAY,4)),0) BETWEEN 40 AND 49 AND GENDER = 0
        GROUP BY C.ID, C.LAST_NAME, C.FIRST_NAME, C.BIRTHDAY, LEFT(@baseDate,4)-LEFT(BIRTHDAY,4)+LEAST(SIGN(RIGHT(@baseDate,4)-RIGHT(BIRTHDAY,4)),0),CASE WHEN C.GENDER = 0 THEN 'M' ELSE 'F' END
    ) X GROUP BY INTEREST_COUNT UNION
    SELECT 0 INTEREST_COUNT,COUNT(1) CNT FROM M_CUSTOMER
        WHERE LEFT(@baseDate,4)-LEFT(BIRTHDAY,4)+LEAST(SIGN(RIGHT(@baseDate,4)-RIGHT(BIRTHDAY,4)),0) BETWEEN 40 AND 49 AND GENDER = 0 AND ID NOT IN (
                SELECT CUSTOMER FROM T_CUSTOMER_INTEREST)) Y ORDER BY INTEREST_COUNT;